### ISSUE TITLE
Shapeless Recipes

### ISSUE THREAD

**Issue by DarkYuan** [Slomaxonical-907/Mazuri#1]
Could the recipes for crafting 1s into 5, and 20s into 100 be shapeless please? As nice as the plus formation is, it's not easy to drag across a crafting grid.

Love the mod btw! Exactly what I was looking for to make a shop in fabric!

**Comment by Slomaxonical-907** [comment]
Wow! I certainly wasn't expecting my first mod to get any feedback (any downloads tbh XD)...  So glad to hear that you liked it!

Anyways, you're right, the plus sign is just unnecessary. Will be shapeless in the next version (never thought there would be any next versions XD).

**Comment by DarkYuan** [comment]
Glad to lend my opinion! I'm actually attempting to make a modded minigame and needed a fabric coin mod. It's also the first time I heard of Modrinth too; you're not on Curse as far as I can tell.

**Comment by Slomaxonical-907** [comment]
Great!  yep, not on CF **yet**.

**Comment by Slomaxonical-907** [comment]
done in 1.0.1
