### ISSUE TITLE
Back-crafting

### ISSUE THREAD

**Issue by DarkYuan** [Slomaxonical-907/Mazuri#2]
The only thing I'd consider this mod to be missing is the ability to craft a coin back into their lesser values.

- 5Ⓜ︎ crafted alone = five 1Ⓜ︎
- 20Ⓜ︎ crafted alone = four 5Ⓜ︎
- 100Ⓜ︎ crafted alone = five 20Ⓜ︎

As a side note, a 10Ⓜ︎ might not be a bad idea

**Comment by Slomaxonical-907** [comment]
I just don't know why I didn't add back-crafting. Will do along with the shapeless feature next version.

As for the 10 coin, I'll have to think about it... I don't think adding another coin without an ore behind it is a good idea... we'll see.
I have to say though that I won't be able to work on modding the coming week (sry for that :( )

**Comment by DarkYuan** [comment]
Actually, as for the value of the coins, it seems like iron should smelt into a 5 coin instead. Cause it's like saying finding one gold ore is worth as much as finding 20 iron ore currently.

**Comment by Slomaxonical-907** [comment]
At first I actually had it like that... Then I remember I looked at the ores frequency (ores/chunk) and 1 to 5 ratio didn't make sense since iron ore is way more common.

Though I will add nether gold ore to equal overworld ones... so values become alright?

**Comment by Slomaxonical-907** [comment]
also in 1.0.1
